const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>'&#'+c.charCodeAt(0)+';');
const API_BASE_URL=window.API_BASE_URL||'http://localhost:5000/api';
const PN={Critical:'C',High:'H',Medium:'M',Low:'L'},PO={Critical:0,High:1,Medium:2,Low:3};
const PC={Critical:'#dc2626',High:'#c2410c',Medium:'#b45309',Low:'#15803d'};
const TEAMS=['Electrical Team','Plumbing Team','Housekeeping','Security','Hostel Supervisor'];
const ST=['Submitted','Assigned','In Progress','Resolved','Closed'];
const CATS=['Electrical','Plumbing','Water Supply','Internet/Wi-Fi','Cleaning','Furniture','Food/Mess','Security','Room Maintenance','Other'];
const AUTH={token:sessionStorage.getItem('hosteldesk_token'),user:JSON.parse(sessionStorage.getItem('hosteldesk_user')||'null')};
const S={v:'land',tab:'home',wt:'ov',sel:null,f:{q:'',p:'',s:'',c:'',b:'',o:'ai'},data:[],overview:null,analytics:null,insights:[]};
const LG='<span class="lg"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 21V8l7-4 6 3v14M9 21v-5h4v5M8 11h1M12 11h1"/><path d="M20 3v4M18 5h4"/></svg></span>';
const FL=['Student complaint','Language understanding','Category classification','Priority prediction','AI confidence','Recommended action','Warden resolution'];
const flow=()=>FL.map((x,i)=>`<div class="st" style="animation-delay:${i}s"><b class="gt">${i+1}</b>${x}</div>`).join('');
const pb=p=>`<span class="bd" style="background:${PC[p]||'#64748b'}">${esc(p)}</span>`;
const sb=s=>`<span class="bd" style="background:${{Submitted:'#475569',Assigned:'#7c3aed','In Progress':'#2563eb',Resolved:'#15803d',Closed:'#334155'}[s]||'#475569'}">${esc(s)}</span>`;
const empty=(e,t,s)=>`<div class="cd" style="text-align:center;padding:40px"><div style="font-size:40px">${e}</div><b>${t}</b><div class="mu">${s}</div></div>`;
const kp=(l,v,c,x)=>`<div class="cd"><div class="mu" style="font-size:13px">${l}</div><div style="font-size:30px;font-weight:800;color:${c||'var(--tx)'}" data-n="${v}">${v}</div>${x||''}</div>`;
function toast(m){const e=document.createElement('div');e.className='t';e.textContent=m;$('#ts').append(e);setTimeout(()=>e.remove(),2600)}
function mdl(h){if(h){$('#mb').innerHTML=h;$('#md').classList.add('on')}else $('#md').classList.remove('on')}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(AUTH.token)headers.Authorization='Bearer '+AUTH.token;const r=await fetch(API_BASE_URL+path,{...opt,headers});let j={};try{j=await r.json()}catch{}if(r.status===401){logout(false);throw Error(j.message||'Please log in again.')}if(!r.ok||j.success===false)throw Error(j.message||'Request failed');return j.data}
function saveAuth(d){AUTH.token=d.token;AUTH.user=d.user;sessionStorage.setItem('hosteldesk_token',d.token);sessionStorage.setItem('hosteldesk_user',JSON.stringify(d.user))}
function logout(show=true){AUTH.token=null;AUTH.user=null;sessionStorage.removeItem('hosteldesk_token');sessionStorage.removeItem('hosteldesk_user');S.v='land';S.sel=null;if(show)toast('Logged out');draw()}
function login(role){mdl(`<h3 style="margin-top:0">${role==='WARDEN'?'Warden':'Student'} login</h3><p class="mu">Use your HostelDesk account.</p><input id="le" class="in" type="email" placeholder="Email" value="${role==='WARDEN'?'warden@hosteldesk.demo':'student@hosteldesk.demo'}"><input id="lp" class="in" style="margin-top:10px" type="password" placeholder="Password" value="HostelDesk@2026!"><div class="fl" style="margin-top:14px"><button class="btn" onclick="doLogin('${role}')">Login</button><button class="btn o" onclick="mdl()">Cancel</button></div><div class="mu" style="font-size:12px;margin-top:12px">Demo accounts are for development only.</div>`)}
async function doLogin(role){try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#le').value,password:$('#lp').value})});if(role==='WARDEN'&&!['WARDEN','ADMIN'].includes(d.user.role))throw Error('This account is not a warden account.');saveAuth(d);mdl();go(role==='WARDEN'?'ward':'stu',role==='WARDEN'?'ov':'home');toast('✓ Login successful')}catch(e){toast('⚠ '+e.message)}}
function requireRole(role,cb){if(!AUTH.user)return login(role);if(role==='WARDEN'&&!['WARDEN','ADMIN'].includes(AUTH.user.role)){toast('⚠ Warden access required.');return login('WARDEN')}cb()}
function go(v,t){if(v==='stu')return requireRole('STUDENT',()=>{S.v='stu';S.tab=t||'home';loadStudent().then(draw).catch(e=>toast(e.message))});if(v==='ward')return requireRole('WARDEN',()=>{S.v='ward';S.wt=t||'ov';loadWarden().then(draw).catch(e=>toast(e.message))});S.v='land';S.sel=null;draw()}
async function loadStudent(){S.data=await api('/complaints/my')}
async function loadWarden(){S.data=await api('/complaints');S.overview=await api('/dashboard/overview');if(S.wt==='ana')S.analytics=await api('/analytics/overview');if(S.wt==='ins')S.insights=await api('/analytics/insights')}
function draw(){$('#dr').classList.remove('on');$('#app').innerHTML=S.v==='land'?land():S.v==='stu'?stu():ward();after();scrollTo(0,0)}
function after(){document.querySelectorAll('[data-n]').forEach(e=>e.textContent=e.dataset.n);}
const land=()=>`<div class="w"><nav class="nav">${LG}<b style="font-size:18px">HostelDesk AI</b><span class="sp"></span><a class="lk" href="#top">Home</a><a class="lk" href="#h">How it works</a><a class="lk" href="#ai">AI classification</a><button class="btn o" onclick="go('stu')">Student Portal</button><button class="btn" onclick="go('ward')">Warden Portal</button></nav><section id="top" class="hero"><div><p class="mu" style="margin:0 0 10px">AI-powered hostel management</p><h1>Your Hostel Problem.<br><span class="gt">AI Knows What To Do.</span></h1><p class="mu" style="max-width:520px">Report hostel issues in seconds. HostelDesk AI automatically understands, classifies, and prioritizes every complaint so the right problem gets the right attention at the right time.</p><div class="fl"><button class="btn" onclick="go('stu','rep')">Report a Problem</button><button class="btn o" onclick="go('ward')">Open Warden Dashboard</button></div></div><div class="cd"><b>“Water has stopped in the Block B bathrooms since morning.”</b>${flow()}</div></section><section id="ai" class="cd" style="padding:26px;margin:10px 0 30px;border-color:#06b6d466;box-shadow:0 0 40px #06b6d422"><h2 style="margin-top:0">See AI in Action</h2><p class="mu">Try the same local classification engine used when complaints are submitted.</p><textarea id="lt" class="in" rows="3">There is a strong burning smell from the electrical socket in Room C-312 and I saw a small spark.</textarea><div class="fl" style="margin:12px 0"><button class="btn" onclick="analyzeDemo()">Analyze Complaint</button></div><div id="lr"></div></section><section id="h"><h2>How it works</h2><div class="grid">${[['Describe it','Type the problem in your own words.'],['AI sorts it','Category, priority and confidence are predicted locally.'],['Warden acts','Urgent issues rise to the priority queue.']].map(x=>`<div class="cd"><b>${x[0]}</b><div class="mu">${x[1]}</div></div>`).join('')}</div><h3 style="margin-top:24px">How AI decides priority</h3><div class="grid">${['Critical','High','Medium','Low'].map((x,i)=>`<div class="cd" style="border-top:4px solid ${PC[x]}"><b>${x}</b><div class="mu" style="font-size:13px">${['Safety hazards and serious emergencies','Essential services unavailable or affecting many students','Important but not immediately dangerous','Minor inconvenience or non-urgent requests'][i]}</div></div>`).join('')}</div></section><footer class="mu" style="padding:34px 0;text-align:center">Smarter Complaints. Faster Resolutions. Better Hostels.</footer></div>`;
async function analyzeDemo(){const t=$('#lt').value.trim();if(t.length<10)return toast('⚠ Type a complaint first.');try{const c=await api('/complaints/analyze',{method:'POST',body:JSON.stringify({description:t,roomNumber:'C-312'})});$('#lr').innerHTML=res(c);toast('✓ Local classification completed')}catch(e){toast('⚠ '+e.message)}}
function res(c){return `<div style="animation:up .4s"><div class="grid" style="margin:12px 0">${[['Category',c.category],['Priority',pb(c.priority)],['Affected area',c.block?'Block '+c.block:'Common area'],['AI confidence',c.confidence+'%']].map(x=>`<div><div class="mu" style="font-size:12px">${x[0]}</div><b>${x[1]}</b></div>`).join('')}</div><div class="pb"><i data-w="${c.confidence}%"></i></div><p><b>AI reasoning</b><br><span class="mu">Detected a ${esc(c.category)} issue${c.affectedStudents>1?' affecting '+c.affectedStudents+' students':''}. Marked ${esc(c.priority)} priority because it points to ${esc(c.reason)}.</span></p><p><b>Recommended action</b><br><span class="mu">${esc(c.recommendedAction)}</span></p><p><b>Expected response:</b> ${esc(c.expectedResponse)}</p></div>`}
const mine=()=>S.data||[];const cl=a=>a.length?a.map(c=>`<div class="cd fl" style="margin:8px 0;cursor:pointer" onclick="tl('${c.id}')"><div style="flex:1;min-width:200px"><div class="mu" style="font-size:12px">${esc(c.id)} · ${esc(c.category)} · ${ago(c.createdAt)}</div><b>${esc(c.text)}</b></div>${pb(c.priority)}${sb(c.status)}<span class="mu" style="font-size:13px">${c.status==='Submitted'?'Awaiting assignment':esc(c.team||'')}</span></div>`).join(''):empty('📭','No complaints yet','Report a problem and it will show up here.');
function ago(d){const m=Math.max(0,Math.round((Date.now()-new Date(d))/60000));return m<1?'Just now':m<60?m+' min ago':m<1440?Math.floor(m/60)+' hr ago':Math.floor(m/1440)+' d ago'}
function stu(){const T=[['home','Dashboard'],['rep','Report a problem'],['my','My complaints']],m=mine(),o=m.filter(c=>!['Resolved','Closed'].includes(c.status));const pg=S.tab==='rep'?`<h2>Report a problem</h2><div class="cd"><textarea id="tx" class="in" rows="5" maxlength="500" placeholder="Describe your problem in your own words..."></textarea><div class="mu" style="text-align:right;font-size:12px"><span id="cc">0</span>/500</div><div class="grid" style="margin:10px 0"><select id="lc" class="in">${['Hostel Block A','Hostel Block B','Hostel Block C','Hostel Block D','Mess','Common Area','Washroom','Laundry','Other'].map(x=>`<option>${x}</option>`).join('')}</select><input id="rm" class="in" placeholder="Room number (e.g. C-312)"></div><label id="up" class="cd" style="display:block;text-align:center;border-style:dashed;cursor:pointer">📷 Upload a photo of the issue (JPG, PNG)<div class="mu" style="font-size:12px">Photo storage is not enabled in this deployment.</div><input id="photo" type="file" accept="image/png,image/jpeg" hidden></label><label class="fl" style="margin:12px 0"><input type="checkbox" id="anon"> Submit anonymously</label><div class="fl"><button class="btn" onclick="sub()">Analyze &amp; Submit Complaint</button><button class="btn o" onclick="demo()">Try AI Demo</button></div></div>`:S.tab==='my'?`<h2>My complaints</h2>${cl(m)}`:`<h2 style="margin:6px 0 0">Good morning, ${esc(AUTH.user?.name||'Student')} 👋</h2><p class="mu" style="margin-top:2px">How can HostelDesk help you today?</p><div class="grid">${kp('Open complaints',o.length)}${kp('In progress',m.filter(c=>c.status==='In Progress').length,'#2563eb')}${kp('Resolved',m.filter(c=>['Resolved','Closed'].includes(c.status)).length,'#15803d')}${kp('High priority',o.filter(c=>['Critical','High'].includes(c.priority)).length,'#dc2626')}</div><div class="cd fl" style="margin:14px 0"><div style="flex:1;min-width:200px"><b>Something wrong in your hostel?</b><div class="mu">Describe it in your own words and the local AI does the rest.</div></div><button class="btn" onclick="go('stu','rep')">Report a Problem</button></div><h3>Recent complaints</h3>${cl(m.slice(0,3))}`;return `<div class="w"><nav class="nav">${LG}<b style="font-size:18px">HostelDesk AI</b><span class="sp"></span>${T.map(t=>`<button class="lk" style="${S.tab===t[0]?'color:var(--tx);border-bottom:2px solid #06b6d4':''}" onclick="go('stu','${t[0]}')">${t[1]}</button>`).join('')}<span class="mu">${esc(AUTH.user?.email||'')}</span><button class="btn o" onclick="logout()">Logout</button><button class="btn o" onclick="go('ward')">Warden Portal</button></nav><main style="animation:up .3s;padding-bottom:30px">${pg}</main></div>`}
function demo(){$('#tx').value='There is a strong burning smell from the electrical socket in Room C-312 and I saw a small spark.';$('#cc').textContent=$('#tx').value.length;$('#rm').value='C-312';$('#lc').value='Hostel Block C';toast('🤖 Demo complaint loaded')}
async function sub(){const t=$('#tx').value.trim();if(t.length<10)return toast('⚠ Please describe the problem in a few more words.');mdl(`<h3 style="margin-top:0">🤖 Local AI is analyzing your complaint…</h3><div id="ar"><div class="sp2"></div></div>`);try{const c=await api('/complaints/analyze',{method:'POST',body:JSON.stringify({description:t,roomNumber:$('#rm').value.trim()||$('#lc').value})});$('#ar').innerHTML=res(c);$('#mb').insertAdjacentHTML('beforeend','<div class="fl" style="margin-top:14px"><button class="btn" onclick="fin()">Submit Complaint</button><button class="btn o" onclick="mdl()">Edit Complaint</button></div>');window.__pending=c;toast('✓ Classification completed.')}catch(e){toast('⚠ '+e.message)}}
async function fin(){try{const c=await api('/complaints',{method:'POST',body:JSON.stringify({description:$('#tx').value.trim(),location:$('#lc').value,roomNumber:$('#rm').value.trim()||$('#lc').value,isAnonymous:$('#anon').checked})});mdl();toast('✓ Complaint submitted successfully.');await loadStudent();go('stu','my')}catch(e){toast('⚠ '+e.message)}}
async function tl(id){try{const c=await api('/complaints/'+encodeURIComponent(id));const h=c.history||[];mdl(`<div class="fl"><b>${esc(c.id)}</b>${pb(c.priority)}${sb(c.status)}</div><h3>${esc(c.text)}</h3><div class="mu">${esc(c.category)} · Room ${esc(c.room||'—')}</div><h4>AI analysis</h4>${res(c)}<h4>Status history</h4>${h.map(x=>`<div class="fl" style="margin:6px 0"><b>✓</b>${esc(x.newStatus||'Created')}<span class="mu">${esc(x.comment||'')}</span></div>`).join('')}<div class="fl"><button class="btn o" onclick="toast('✉️ Message sent to the Warden');mdl()">Message Warden</button>${!['Resolved','Closed'].includes(c.status)?`<button class="btn" onclick="studentResolve('${c.id}')">Mark as Resolved</button>`:''}</div>`)}catch(e){toast('⚠ '+e.message)}}
async function studentResolve(id){try{await api('/complaints/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status:'Resolved'})});mdl();await loadStudent();go('stu','my');toast('✓ Status updated to Resolved.')}catch(e){toast('⚠ '+e.message)}}
const card=c=>`<div class="cd" style="margin:10px 0;border-left:5px solid ${PC[c.priority]||'#64748b'}"><div class="fl">${pb(c.priority)}${sb(c.status)}<span class="sp"></span><span class="mu" style="font-size:12px">${esc(c.id)}</span></div><b style="font-size:16px;display:block;margin:6px 0">${esc(c.text)}</b><div class="fl mu" style="font-size:13px"><span>📍 ${esc(c.room||c.location||'—')}</span><span>🏷 ${esc(c.category)}</span><span>🤖 ${c.confidence}% confidence</span><span>👥 ${c.affectedStudents} student${c.affectedStudents>1?'s':''}</span></div><div class="fl" style="margin-top:10px"><button class="btn o" onclick="op('${c.id}')">View Details</button><button class="btn" onclick="op('${c.id}')">Assign</button></div></div>`;
const tb=a=>`<div class="cd" style="overflow-x:auto;padding:6px"><table style="width:100%;border-collapse:collapse;font-size:13px;min-width:760px"><tr class="mu" style="text-align:left">${['ID','Problem','Student','Room','Category','Priority','Status','Team'].map(h=>`<th style="padding:8px">${h}</th>`).join('')}</tr>${a.map(c=>`<tr onclick="op('${c.id}')" style="cursor:pointer;border-top:1px solid var(--bd)">${[c.id,c.text.slice(0,46)+(c.text.length>46?'…':''),c.isAnonymous?'Anonymous':c.student,c.room,c.category,pb(c.priority),sb(c.status),c.status==='Submitted'?'—':c.team||'—'].map(x=>`<td style="padding:8px">${typeof x==='string'&&x.startsWith('<span')?x:esc(x)}</td>`).join('')}</tr>`).join('')}</table></div>`;
function flt(open){const f=S.f,q=f.q.toLowerCase();return S.data.filter(c=>(!open||!['Resolved','Closed'].includes(c.status))&&(!f.p||c.priority===f.p)&&(!f.s||c.status===f.s)&&(!f.c||c.category===f.c)&&(!f.b||c.block===f.b)&&(!q||(c.id+' '+(c.student||'')+' '+(c.room||'')+' '+c.category+' '+c.text).toLowerCase().includes(q))).sort((a,b)=>f.o==='new'?new Date(b.createdAt)-new Date(a.createdAt):PO[a.priority]-PO[b.priority]||new Date(a.createdAt)-new Date(b.createdAt))}
function rs(){const a=flt(S.wt==='q');return a.length?(S.wt==='q'?a.map(card).join(''):tb(a)):empty('🔍','No matching complaints','Try a different keyword or clear a filter.')}
function sf(){if(S.wt!=='q'&&S.wt!=='all'){S.wt='q';loadWarden().then(draw)}else {const r=$('#res');if(r)r.innerHTML=rs()}}
const fb=()=>`<div class="fl" style="margin-bottom:12px">${[['p','Priority',['Critical','High','Medium','Low']],['s','Status',ST.slice(0,4)],['c','Category',CATS],['b','Block',['A','B','C','D']]].map(f=>`<select class="in" style="width:auto" onchange="S.f.${f[0]}=this.value;sf()"><option value="">${f[1]}: All</option>${f[2].map(o=>`<option ${S.f[f[0]]===o?'selected':''}>${o}</option>`).join('')}</select>`).join('')}<select class="in" style="width:auto" onchange="S.f.o=this.value;sf()"><option value="ai">Sort by AI priority</option><option value="new" ${S.f.o==='new'?'selected':''}>Newest first</option></select></div><div id="res">${rs()}</div>`;
function ana(){const a=S.analytics||{},pr=a.priorities||{},bl=a.blocks||{},cn=a.categories||{},t=Object.values(cn).reduce((x,y)=>x+y,0);return `<h2 style="margin:0">Hostel Intelligence</h2><p class="mu">Database-backed analytics from real complaints.</p><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr))"><div class="cd"><b>Complaints by category</b>${bars(cn)}</div><div class="cd"><b>Priority distribution</b>${bars(pr)}</div><div class="cd"><b>Hostel block analysis</b>${bars(Object.fromEntries(Object.entries(bl).map(([k,v])=>['Block '+k,v])))}</div><div class="cd"><b>Total records</b><div style="font-size:36px;font-weight:800">${t}</div><div class="mu">No hardcoded chart values.</div></div></div>`}
function bars(m){const mx=Math.max(...Object.values(m),1);return Object.entries(m).map(([k,v])=>`<div class="fl" style="margin:8px 0"><span style="width:100px;font-size:13px">${esc(k)}</span><div class="pb" style="flex:1;height:14px"><i data-w="${v/mx*100}%"></i></div><b>${v}</b></div>`).join('')}
function wp(){const t=S.wt,op_=S.data.filter(c=>!['Resolved','Closed'].includes(c.status));if(t==='q')return `<h2 style="margin:0">AI Priority Queue</h2><p class="mu">Complaints automatically ranked by urgency and impact.</p>${fb()}`;if(t==='all')return `<h2 style="margin:0">All Complaints</h2><p class="mu">Every complaint, searchable and filterable.</p>${fb()}`;if(t==='ins')return `<h2 style="margin:0">AI Insights</h2><p class="mu">Patterns generated from stored complaint data.</p><div class="cd" style="margin-bottom:14px"><b>How every complaint flows through the AI</b>${flow()}</div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr))">${(S.insights||[]).map(i=>`<div class="cd" style="border-top:4px solid #4f46e5"><div style="font-size:26px">${i.icon}</div><b>${esc(i.title)}</b><p class="mu">${esc(i.text)}</p></div>`).join('')}</div>`;if(t==='ana')return ana();const c=S.data.filter(x=>x.priority==='Critical'&&x.status==='Submitted').sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))[0];const o=S.overview||{};return `<h2 style="margin:0">Hostel Overview</h2><p class="mu">Here's what needs your attention today.</p>${c?`<div class="al"><span style="font-size:32px">🚨</span><div style="flex:1;min-width:200px"><b style="font-size:18px">Critical Issue Detected</b><div>Possible ${esc(c.category.toLowerCase())} safety hazard · Block ${esc(c.block||'—')} · Room ${esc(c.room||'—')} · AI confidence ${c.confidence}%</div><b>Immediate attention recommended</b></div><button class="btn" style="background:#fff;color:#b91c1c" onclick="op('${c.id}')">View Complaint</button><button class="btn" style="background:#0007" onclick="asg('${c.id}','${c.team||'Hostel Supervisor'}')">Assign Now</button></div>`:''}<div class="grid" style="margin:14px 0">${kp('Total complaints',o.totalComplaints||0)}${kp('Pending',o.pending||0,'#b45309')}${kp('High priority',o.highPriority||0,'#dc2626')}${kp('Resolved',o.resolved||0,'#15803d')}</div><h3>⚡ AI Priority Queue</h3><p class="mu">Complaints automatically ranked by urgency and impact.</p>${flt(true).slice(0,5).map(card).join('')}<button class="btn o" onclick="go('ward','q')">View full queue</button>`}
function ward(){const W=[['ov','Overview','📊'],['q','Priority Queue','⚡'],['all','All Complaints','📋'],['ins','AI Insights','🤖'],['ana','Analytics','📈']];return `<div class="wl"><aside class="sb"><div class="fl nb" style="padding:6px 10px 18px;color:#fff">${LG}<b>HostelDesk AI</b></div>${W.map(n=>`<a class="${S.wt===n[0]?'on':''}" onclick="go('ward','${n[0]}')">${n[2]} ${n[1]}</a>`).join('')}<a onclick="go('stu')">🎓 Student Portal</a><a onclick="logout()">🚪 Logout</a></aside><div class="mn"><div class="fl" style="margin-bottom:14px"><input id="sq" class="in" style="flex:1;min-width:140px;max-width:380px" placeholder="Search complaints..." value="${esc(S.f.q)}" oninput="S.f.q=this.value;sf()"><span class="sp"></span><div><b>${esc(AUTH.user?.name||'Warden')}</b><div class="mu" style="font-size:12px">${esc(AUTH.user?.role||'WARDEN')}</div></div></div><main style="animation:up .3s">${wp()}</main></div></div>`}
async function asg(id,team){try{await api('/complaints/'+encodeURIComponent(id)+'/assign',{method:'POST',body:JSON.stringify({team})});toast('✓ Complaint assigned to '+team+'.');await loadWarden();draw()}catch(e){toast('⚠ '+e.message)}}
async function setSt(id,status){try{await api('/complaints/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})});toast('✓ Status updated to '+status+'.');await loadWarden();draw();op(id)}catch(e){toast('⚠ '+e.message)}}
async function op(id){try{const c=await api('/complaints/'+encodeURIComponent(id));S.sel=id;$('#dr').innerHTML=`<div class="fl"><h3 style="margin:0">Complaint ${esc(c.id)}</h3><span class="sp"></span><button class="btn o" onclick="$('#dr').classList.remove('on')">✕</button></div><div class="fl" style="margin:10px 0">${pb(c.priority)}${sb(c.status)}</div><div class="mu">Student: <b style="color:var(--tx)">${esc(c.isAnonymous?'Anonymous':c.student)}</b> · Room ${esc(c.room||'—')} · ${esc(c.category)}</div><h4>Original complaint</h4><div class="cd" style="font-style:italic">“${esc(c.text)}”</div><h4>AI analysis</h4>${res(c)}<h4>Assignment</h4><div class="fl"><select id="as" class="in" style="flex:1">${TEAMS.map(t=>`<option ${t===c.team?'selected':''}>${t}</option>`).join('')}</select><button class="btn" onclick="asg('${c.id}',$('#as').value)">Assign Complaint</button></div><h4>Status</h4><div class="fl"><select id="ss" class="in" style="flex:1">${ST.map(t=>`<option ${t===c.status?'selected':''}>${t}</option>`).join('')}</select><button class="btn" onclick="setSt('${c.id}',$('#ss').value)">Update Status</button></div><h4>History</h4>${(c.history||[]).map(h=>`<div class="fl" style="margin:6px 0"><b>✓</b><span>${esc(h.newStatus||'Created')}</span><span class="mu">${esc(h.changedBy||'')} ${esc(h.comment||'')}</span></div>`).join('')}<h4>Comments</h4>${(c.comments||[]).map(x=>`<div class="cd" style="margin:6px 0"><b>${esc(x.author)}</b><div class="mu">${esc(x.body)}</div></div>`).join('')}<div class="fl"><input id="cm" class="in" placeholder="Add a comment"><button class="btn" onclick="comment('${c.id}')">Comment</button></div>`;$('#dr').classList.add('on')}catch(e){toast('⚠ '+e.message)}}
async function comment(id){const body=$('#cm').value.trim();if(!body)return;try{await api('/complaints/'+encodeURIComponent(id)+'/comments',{method:'POST',body:JSON.stringify({body})});toast('✓ Comment added');op(id)}catch(e){toast('⚠ '+e.message)}}
draw();
