import { prisma } from '../config/db.js'; import { classify } from '../classifier/index.js'; import { complaintSchema,assignSchema,statusSchema,patchComplaintSchema,commentSchema } from '../validators/schemas.js'; import { ok,fail } from '../utils/api.js'; import { categoryDb,teamDb,statusDb,fromStatusDb,fromTeamDb } from '../utils/enums.js'; import { serializeComplaint } from '../services/serializers.js';
const include={student:{select:{id:true,name:true,studentId:true}},assignedTo:{select:{id:true,name:true}},comments:{include:{author:{select:{name:true,role:true}}},orderBy:{createdAt:'asc'}}};
function whereQuery(q){const where={};if(q.status)where.status=statusDb[q.status]||q.status;if(q.priority)where.priority=q.priority;if(q.category)where.category=categoryDb[q.category]||q.category;if(q.block)where.hostelBlock=q.block.toUpperCase();if(q.q)where.OR=[{complaintCode:{contains:q.q,mode:'insensitive'}},{description:{contains:q.q,mode:'insensitive'}},{roomNumber:{contains:q.q,mode:'insensitive'}},{student:{name:{contains:q.q,mode:'insensitive'}}}];return where}
export async function create(req,res){const p=complaintSchema.safeParse(req.body);if(!p.success)return fail(res,'Invalid complaint',422,p.error.flatten());const d=p.data,c=classify(d.description,d.roomNumber||d.location||'');const complaint=await prisma.complaint.create({data:{complaintCode:`HD-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`,studentId:req.user.id,description:d.description,location:d.location,roomNumber:d.roomNumber,category:categoryDb[c.category],priority:c.priority,confidence:c.confidence,assignedTeam:teamDb[c.team],status:'Submitted',affectedStudents:c.affectedStudents,hostelBlock:c.block||req.user.hostelBlock,recommendedAction:c.recommendedAction,expectedResponse:c.expectedResponse,aiReasoning:c.reason,isAnonymous:d.isAnonymous,photoUrl:d.photoUrl},include});await prisma.complaintHistory.create({data:{complaintId:complaint.id,changedBy:req.user.id,newStatus:'Submitted',comment:'Complaint submitted and classified automatically.'}});return ok(res,serializeComplaint(complaint,req.user),201)}
export async function listMine(req,res){const rows=await prisma.complaint.findMany({where:{studentId:req.user.id},include,orderBy:{createdAt:'desc'}});return ok(res,rows.map(x=>serializeComplaint(x,req.user)))}
export async function listAll(req,res){const rows=await prisma.complaint.findMany({where:whereQuery(req.query),include,orderBy:req.query.sort==='new'?[{createdAt:'desc'}]:[{priority:'asc'},{createdAt:'asc'}]});return ok(res,rows.map(x=>serializeComplaint(x,req.user)))}
async function getForUser(id,user){const c=await prisma.complaint.findUnique({where:{complaintCode:id},include:{...include,history:{include:{actor:{select:{name:true,role:true}}},orderBy:{createdAt:'asc'}}}});if(!c)return null;if(user.role==='STUDENT'&&c.studentId!==user.id)return 'forbidden';return c}
export async function getOne(req,res){const c=await getForUser(req.params.id,req.user);if(c==='forbidden')return fail(res,'You cannot access this complaint',403);if(!c)return fail(res,'Complaint not found',404);return ok(res,{...serializeComplaint(c,req.user),history:c.history.map(h=>({oldStatus:h.oldStatus?fromStatusDb[h.oldStatus]:undefined,newStatus:h.newStatus?fromStatusDb[h.newStatus]:undefined,comment:h.comment,changedBy:h.actor?.name,createdAt:h.createdAt})),comments:c.comments?.map(x=>({body:x.body,author:x.author?.name,role:x.author?.role,createdAt:x.createdAt}))})}
export async function assign(req,res){const p=assignSchema.safeParse(req.body);if(!p.success)return fail(res,'Invalid assignment',422);const c=await prisma.complaint.findUnique({where:{complaintCode:req.params.id}});if(!c)return fail(res,'Complaint not found',404);const next=c.status==='Submitted'?'Assigned':c.status;const updated=await prisma.complaint.update({where:{id:c.id},data:{assignedTeam:teamDb[p.data.team],assignedToId:p.data.assignedToId||null,status:next},include});await prisma.complaintHistory.create({data:{complaintId:c.id,changedBy:req.user.id,oldStatus:c.status,newStatus:next,comment:`Assigned to ${p.data.team}.`}});return ok(res,serializeComplaint(updated,req.user))}
export async function changeStatus(req,res){const p=statusSchema.safeParse(req.body);if(!p.success)return fail(res,'Invalid status',422);const c=await prisma.complaint.findUnique({where:{complaintCode:req.params.id}});if(!c)return fail(res,'Complaint not found',404);if(req.user.role==='STUDENT'&&(c.studentId!==req.user.id||!['Resolved'].includes(p.data.status)))return fail(res,'Students can only mark their own complaint as Resolved',403);const next=statusDb[p.data.status];const resolvedAt=next==='Resolved'?new Date():c.resolvedAt;const updated=await prisma.complaint.update({where:{id:c.id},data:{status:next,resolvedAt},include});await prisma.complaintHistory.create({data:{complaintId:c.id,changedBy:req.user.id,oldStatus:c.status,newStatus:next,comment:p.data.comment||null}});return ok(res,serializeComplaint(updated,req.user))}
export async function patch(req,res){const p=patchComplaintSchema.safeParse(req.body);if(!p.success)return fail(res,'Invalid complaint update',422);const data={};if(p.data.category)data.category=categoryDb[p.data.category];if(p.data.priority)data.priority=p.data.priority;if(p.data.assignedTeam)data.assignedTeam=teamDb[p.data.assignedTeam];const c=await prisma.complaint.findUnique({where:{complaintCode:req.params.id}});if(!c)return fail(res,'Complaint not found',404);const updated=await prisma.complaint.update({where:{id:c.id},data,include});return ok(res,serializeComplaint(updated,req.user))}
export async function history(req,res){const c=await getForUser(req.params.id,req.user);if(c==='forbidden')return fail(res,'Forbidden',403);if(!c)return fail(res,'Complaint not found',404);const h=await prisma.complaintHistory.findMany({where:{complaintId:c.id},include:{actor:{select:{name:true,role:true}}},orderBy:{createdAt:'asc'}});return ok(res,h.map(x=>({oldStatus:x.oldStatus?fromStatusDb[x.oldStatus]:undefined,newStatus:x.newStatus?fromStatusDb[x.newStatus]:undefined,comment:x.comment,changedBy:x.actor.name,createdAt:x.createdAt})))}
export async function comment(req,res){const p=commentSchema.safeParse(req.body);if(!p.success)return fail(res,'Invalid comment',422);const c=await prisma.complaint.findUnique({where:{complaintCode:req.params.id}});if(!c)return fail(res,'Complaint not found',404);if(req.user.role==='STUDENT'&&c.studentId!==req.user.id)return fail(res,'Forbidden',403);const x=await prisma.complaintComment.create({data:{complaintId:c.id,authorId:req.user.id,body:p.data.body},include:{author:{select:{name:true,role:true}}}});return ok(res,{body:x.body,author:x.author,createdAt:x.createdAt},201)}
